package basics.generics;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Coding exercise (JAVA-Generics): Write a Java program to create a generic method that
 * takes a list of numbers and returns the sum of all the even and odd numbers.
 */
public class SumEvenAndOddInList {

    /**
     * Sums the even and odd numbers in the provided list of numbers.
     *
     * @param <T> The type of the elements in the list, which must extend Number (e.g., Integer, Double).
     * @param numList The list of numbers to process.
     * @return A string representing the sum of even and odd numbers in the list.
     */
    public static <T extends Number> String sumEvenOdd(List<T> numList) {

        // Initialize totals for even and odd sums
        int totalEven = 0;
        int totalOdd = 0;

        // Iterate through the list of numbers
        for (int i = 0; i < numList.size(); i++) {
            // Convert the number to an integer value for even/odd comparison
            int value = numList.get(i).intValue();

            // If the value is even, add it to totalEven, otherwise add it to totalOdd
            if (value % 2 == 0) {
                totalEven += value;
            } else {
                totalOdd += value;
            }
        }

        // Return the results as a formatted string
        return "Even Total: " + totalEven + " & Odd Total: " + totalOdd;
    }

    /**
     * Main method to test the sumEvenOdd method with different types of lists (Integer, Double).
     *
     * @param args Command-line arguments (not used in this program).
     */
    public static void main(String[] args) {

        // Lists for different types of numbers
        List<Integer> numListRandom = new ArrayList<>();
        List<Integer> intList = new ArrayList<>();
        List<Double> doubleList = new ArrayList<>();

        // Random number generator to create random integers
        Random random = new Random();
        int bound = 10;

        // Generate a list of random integers between 0 and bound
        for (int i = 0; i < bound; i++) {
            int randomNum = random.nextInt(bound);
            numListRandom.add(randomNum);
        }

        // Manually adding values to the integer list
        intList.add(3);
        intList.add(1);
        intList.add(4);
        intList.add(2);

        // Manually adding values to the double list
        doubleList.add(1.2);
        doubleList.add(3.0);
        doubleList.add(2.0);
        doubleList.add(4.2);
        doubleList.add(5.0);

        // Print and process the list generated by random numbers
        System.out.println("List generated by Random: " + numListRandom);
        System.out.println("Sum of even and odd numbers for Random numbers: " + sumEvenOdd(numListRandom));
        System.out.println();

        // Print and process the list of integers
        System.out.println("List generated by Integer List: " + intList);
        System.out.println("Sum of even and odd numbers for Integer numbers: " + sumEvenOdd(intList));
        System.out.println();

        // Print and process the list of doubles
        System.out.println("List generated by Double List: " + doubleList);
        System.out.println("Sum of even and odd numbers for Double numbers: " + sumEvenOdd(doubleList));
        System.out.println();
    }
}
